In [16]:
import numpy as np
print('hello world ')

hello world 


In [17]:
myarr= np.array([3,4,56,7],np.int8)#int8 number should not be big
myarr
myarr[0]
#if any value is too big then show an error

np.int8(3)

In [18]:
myarr= np.array([[3,4,56,7]])
myarr[0,1]

np.int64(4)

In [21]:
myarr.dtype
myarr.shape

(1, 4)

In [22]:
myarr[0,1]=45
myarr

array([[ 3, 45, 56,  7]])

In [26]:

a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

a1D
a2D
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [27]:
##arry creation :conversion from other Python structure

In [30]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray
listarray.dtype
listarray.shape
listarray.size

9

In [32]:
listarray.shape
listarray
np.array({34,23,89})

array({89, 34, 23}, dtype=object)

In [ ]:
zeros=np.zeros((2,6))#creating array
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
rng=np.arange(6)#ceating a numpy array in 5
rng

array([0, 1, 2, 3, 4, 5])

In [ ]:
lspace=np.linspace(1,5,12)
lspace
#here it gives us 12 randomly floating elements which is 
# start at 1 and end at 5 with same space location 


array([1., 2., 3., 4., 5.])

In [42]:
lspace=np.linspace(1,5,5)#list 
lspace

array([1., 2., 3., 4., 5.])

In [ ]:
emp=np.empty((4,3))
emp
#create a matrix 

array([[1.        , 1.36363636, 1.72727273],
       [2.09090909, 2.45454545, 2.81818182],
       [3.18181818, 3.54545455, 3.90909091],
       [4.27272727, 4.63636364, 5.        ]])

In [48]:
emp_like=np.empty_like((4,5))
emp_like

array([1722551996112,             0])

In [ ]:
ide=np.identity(45)
ide #if i want a big array

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [50]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.reshape(3,33)#32 elements each list 
#arange is 99 so it full fill the value 99 
#if we input small or big range it show an error 
#it not like the 99 value same 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr.ravel()#create a 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.shape#1D array it has 99 element is 

(99,)